image: docker:27.4.1
services:
  - docker:27.4.1-dind
variables:
  DOCKER_TLS_CERTDIR: ""
  apiurl: "http://docker:8198"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    #- echo "Starting the build.."
    #- docker-compose build
    #- echo "Build finished"
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker-compose build
    - docker-compose push

test:
  stage: test
  before_script:
    - apk add --no-cache nodejs npm #curl
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker-compose pull
    - docker-compose up -d #--build
  script:
    - echo "Running tests for the application"
    - cd tests
    - npm install
    - npm test
  after_script:
    - echo "Finished test script"
    - docker-compose down

deploy:
  stage: deploy
  script:
    - echo "Starts the application on GitLab Runner"
    - docker-compose down # if the previous version is running
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker-compose pull
    - docker-compose up -d #--build
    - docker-compose down # remove this when actually put into production
