image: docker:latest
variables:
  name: 'joonatan'

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "TODO build the application"

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "Launching the application for the tests"
    - docker-compose up --build
    - echo "Finished launching the application for the tests"
    - sleep 50
  script:
    - echo "Running tests for the application"
    - cd tests
    - npm install
    - npm test
  after_script:
    - echo "Finished test script"
    - docker-compose down

deploy:
  stage: deploy
  image: docker:latest
  script:
    - echo "TODO deploy into production"
